### ISSUE TITLE
min SDK version 21

### ISSUE THREAD

**Issue by Maxxan** [alorma/Compose-Settings#1]
What is the reason that min SDK version is 23? When you create a compose application the default suggestion is 21. Maybe this library also could be min SDK 21?

**Comment by alorma** [comment]
Hi @Maxxan 

Not really a reason. I configured the project as MinSDK 23 when I created it and never thought of downgrading it.

Would you open a PR to make it point to api 21?

**Comment by alorma** [comment]
Already done
