### ISSUE TITLE
Add support for `dependency`

### ISSUE THREAD

**Issue by ItzNotABug** [alorma/Compose-Settings#100]
See this: https://developer.android.com/reference/android/preference/Preference.html#attr_android:dependency

Alternatively,
an `enabled` state can also be added to allow/disallow interacting with a Setting.

**Comment by alorma** [comment]
Interesting thing... 

I will try to add the enabled feature first so dependency could be mocked by developer.

Thanks

**Comment by alorma** [comment]
Working on #102

**Comment by alorma** [comment]
Hi @ItzNotABug .

Please. Check version 0.18.0, as it contains the ability to disable items.

I not added yet the dependency thing but I think you can achive it by using the new `enabled` param of Settings tiles (both m2 and m3).

**Comment by ItzNotABug** [comment]
Hey @alorma,
I'm trying to use `SettingsListDropdown` but seems like the `enabled` parameter is added to `SettingsList*` components but it is not implemented in m2.

**Comment by alorma** [comment]
Oh...

Maybe I missed it?

Let me add it

**Comment by alorma** [comment]
Ok @ItzNotABug Try now with version `0.19.0`As I've forgot to pass the param to the correct composables 😓

**Comment by ItzNotABug** [comment]
Hey @alorma,
Thanks for the quick updates!

However you missed to update the `SettingsMenuLink` so I created a PR that completes this implementation along with a another misc fix.

**Comment by alorma** [comment]
Releasing 0.20.0. thanks for your contribution
