### ISSUE TITLE
[Feature request] Subtitle heigh optional

### ISSUE THREAD

**Issue by zenyagami** [alorma/Compose-Settings#117]
Currently there is a limitation of the sutitle size, if the text is  more than 2 lines, the subtitle is cutted
example code in `SettingsTileScaffold`
`val maxHeight = if (subtitle == null) 72.dp else 88.dp`
event if my composable supports 3 lines, the max line of `88.dp` make this not possible,  would be great to add as an optional parameter so we can override or as modifier.
Thanks a lot!!

**Comment by alorma** [comment]
Hi @zenyagami !

Can you provide an example screenshot of the problem?

Also, would yo open a PR?

**Comment by zenyagami** [comment]
@alorma Gladly, seems that the issue is in Preference from m3, I created a [PR Here](https://github.com/alorma/Compose-Settings/pull/120)
