### ISSUE TITLE
SettingsList of rememberPreferenceStringSettingState using map

### ISSUE THREAD

**Issue by laeo** [alorma/Compose-Settings#20]
Can u provide another compose component that accepts string state variable, so we can use `rememberPreferenceStringSettingState` directly in ours project? Thanks your great work!

**Comment by EdricChan03** [comment]
Was there a reason why this issue was closed? No such method appears to exist as of the time of writing

**Comment by alorma** [comment]
Feel FREE to repoen it, or opten a pull request with the idea
