### ISSUE TITLE
1.1.0 Release issues

### ISSUE THREAD

**Issue by dessalines** [alorma/Compose-Settings#218]
A few issues I've found:

- `com.github.alorma:compose-settings-ui-m3:1.1.0` is still missing / not deployed.
- Using `com.github.alorma:compose-settings-ui-m3:1.1.0` requires an increase in the minSdk from 21 -> 26 for some reason, and also is missing all the `rememberIntSettingsState` functions.

**Comment by alorma** [comment]
M3 module has been moved to just `ui`, bo more material2 settings.

Mmm. Weird about the minSdk thing, i will check that.

Also weird remember int is missing... Will check tomorrow

**Comment by alorma** [comment]
Hi @dessalines 

I've been checking...

I'm gonna push a version with API 21 later today.

About `rememberIntSettingsState` I'm not sure about that, I just checked and seen that it's included in the `:compose-settings-storage-disk` module... so just add it to your dependencies and you will be able to use it.

**Comment by dessalines** [comment]
Cool, thx!
