### ISSUE TITLE
key in SharedPreferences

### ISSUE THREAD

**Issue by ppareit** [alorma/Compose-Settings#3]
In the original android implementation for PreferenceScreen the key's where retrieved from the SharedPrefernces. The key's where also updated by the Preference, for instance the SwitchPreference with key 'switch' would save its state to the correct SharedPreference.

This was very handy. Is functionality like this planned?

**Comment by alorma** [comment]
You mean that this library handles Shared Preferences internally?

I decided to not do so, as now there's SharedPrefences, preference compat, datastore... Library provides states hoisiting so you get notified when switch or checkbox is updated... and you can implement the save of value however you want
