### ISSUE TITLE
Jetpack DataStore support

### ISSUE THREAD

**Issue by pelmenstar1** [alorma/Compose-Settings#43]
It would be great if the library had the explicit support of Jetpack DataStore. It's doable without the support of the library, but the output code is quite hard to support then.

@alorma What do you think about it?

**Comment by alorma** [comment]
Hi @pelmenstar1 

Sure, I've done some work on that way time ago. But never finished it.

Would you like to open a PR with that addition?

**Comment by pelmenstar1** [comment]
I'm working on it right now.

**Comment by alorma** [comment]
Great! Open a PR when you think it's done and I will review that.

Thank you!

**Comment by alorma** [comment]
Hey @pelmenstar1 !

just updated to compose 1.2.1, so please rebase your WIP branch in order to get all changes:

https://github.com/alorma/Compose-Settings/releases/tag/0.9.0
