### ISSUE TITLE
Material 3

### ISSUE THREAD

**Issue by daimonkor** [alorma/Compose-Settings#64]
Hello. Do you want support Material 3?

**Comment by alorma** [comment]
Surely!

I have the idea to move to material 3 someday... as a separate artifact.

Would you create a pull request with material 3?

**Comment by daimonkor** [comment]
> Surely!
> 
> I have the idea to move to material 3 someday... as a separate artifact.
> 
> Would you create a pull request with material 3?

Hello, sorry, as for me, it is "black box". I can immediate test at pet project). I found that you created pull request before

**Comment by alorma** [comment]
Yes 🤣

I've started with it.

Give me some days to polish details of M3. As I don't have any guidelines on settings with M3.

**Comment by daimonkor** [comment]
> Yes 🤣
> 
> I've started with it.
> 
> Give me some days to polish details of M3. As I don't have any guidelines on settings with M3.

Thanks a lot.

**Comment by alorma** [comment]
Hey @daimonkor .

I've just released a new version [0.13.0](https://github.com/alorma/Compose-Settings/releases/tag/0.13.0) with a new artifact (module).

You can try it with:

```
implementation 'com.github.alorma:compose-settings-ui-m3:0.13.0'
```

Please, try it and give me any issue that you find!

**Comment by daimonkor** [comment]
> Hey @daimonkor .
> 
> I've just released a new version [0.13.0](https://github.com/alorma/Compose-Settings/releases/tag/0.13.0) with a new artifact (module).
> 
> You can try it with:
> 
> ```
> implementation 'com.github.alorma:compose-settings-ui-m3:0.13.0'
> ```
> 
> Please, try it and give me any issue that you find!

Thanks a lot, in process

**Comment by daimonkor** [comment]
@alorma 
Hm, can not recompose switchers component when changed language

```java
@Composable
fun SetLanguage(locale: Locale) {
    val configuration = LocalConfiguration.current
    configuration.setLocale(locale)
    val resources = LocalContext.current.resources
    resources.updateConfiguration(configuration, resources.displayMetrics)
}
```

```java
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun Settings(
    navController: NavController,
    isDarkMode: Boolean,
) {
val darkSwitcherState = rememberBooleanSettingState(isDarkMode)
SettingsSwitch(
                state = darkSwitcherState,
                modifier = Modifier
                    .background(MaterialTheme.colorScheme.background),
                icon = {
                    Icon(
                        imageVector = Icons.Default.DarkMode,
                        contentDescription = stringResource(R.string.dark_mode),
                        tint = MaterialTheme.colorScheme.onBackground
                    )
                },
                title = {
                    Text(
                        stringResource(R.string.dark_mode),
                        color = MaterialTheme.colorScheme.onBackground
                    )
                },
                onCheckedChange = onDarkModeChange
            )
}
```
Looks like https://prnt.sc/GG-Owt-VbALQ

**Comment by daimonkor** [comment]
@alorma Hello, I mean recompose does not work for your switchers when changed configuration (locale)
