### ISSUE TITLE
SettingsList not taking full width

### ISSUE THREAD

**Issue by dessalines** [alorma/Compose-Settings#86]
Can't figure out why this is.

Example:

![Screenshot_2022-12-20-10-53-58-164_com jerboa](https://user-images.githubusercontent.com/930215/208711084-d23fdb4a-127e-4843-9d8c-81eaab514e1f.png)

Code:

```kt
Column {
  SettingsList(...)
  SettingsSlider(...)
}
```

**Comment by alorma** [comment]
![2022-12-20 18 03 34](https://user-images.githubusercontent.com/887462/208724156-7799b474-b2d4-4c8b-bd41-0e0c3d91b3db.gif)

It's working here.

Maybe you have to add `Modifier.fillMaxWidth()` ?

**Comment by alorma** [comment]
![Captura de Pantalla 2022-12-20 a las 18 04 46](https://user-images.githubusercontent.com/887462/208724337-f5e14ded-931e-4cd5-b679-5ad452109b46.png)

Anyway, that extra "space" on the right is because of `action` param, that you can use to add a custom icon (or text, or whatever) as a separate actionable item

**Comment by dessalines** [comment]
I'm confused... action should just be the action that's performed when you make a new selection right? Why would that need to be a composable thing like a button? For a settings list, all you care about is the dialog with your list options, I don't see why it needs a 2nd icon.

**Comment by alorma** [comment]
![Screenshot_20221221-181121.png](https://user-images.githubusercontent.com/887462/208964242-d036e4e3-23c1-4422-a6cd-576e1dd48d9e.png)

Check this example from bluethoot settings.

Action here is the gear part of the settings tile, so you can jave different parts, main setting and secondary

**Comment by dessalines** [comment]
Where is that example code?

**Comment by alorma** [comment]
You can check the app sample, and there check on MenuLinks
