### ISSUE TITLE
Add a Color picker setting

### ISSUE THREAD

**Issue by dessalines** [alorma/Compose-Settings#87]
This would be extremely useful in an application I'm building.

**Comment by alorma** [comment]
You can build it yourself.

Just use `SettingsMenuLink` and use `action` param to preview de selectes color


I don't think this will fit on the main library... But I'm open to have a separate module for it.

**Comment by dessalines** [comment]
Sounds good, I should be able to get to it within a few weeks.

**Comment by alorma** [comment]
Feel free to open a PR when you have something to share!

**Comment by dessalines** [comment]
If you would, leave this issue open, then when I add this, I can close the issue with a commit.
